--------------------------------------------------------
--  파일이 생성됨 - 토요일-8월-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CBOARD
--------------------------------------------------------

  CREATE TABLE "MADANG"."CBOARD" 
   (	"NUM" NUMBER(*,0), 
	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"SUBJECT" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"REGIST_DAY" VARCHAR2(30 BYTE), 
	"HIT" NUMBER(*,0), 
	"IP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MADANG.CBOARD
SET DEFINE OFF;
Insert into MADANG.CBOARD (NUM,ID,NAME,SUBJECT,CONTENT,REGIST_DAY,HIT,IP) values (5,'javacosme','kimcos','shipship','plz ship','2018/09/29',11,'22');
Insert into MADANG.CBOARD (NUM,ID,NAME,SUBJECT,CONTENT,REGIST_DAY,HIT,IP) values (6,'metic','kimmetic','product trouble','nooo','2019/07/11',2,'2635');
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADANG"."BOARD_PK" ON "MADANG"."CBOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CBOARD
--------------------------------------------------------

  ALTER TABLE "MADANG"."CBOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MADANG"."CBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MADANG"."CBOARD" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "MADANG"."CBOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MADANG"."CBOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MADANG"."CBOARD" MODIFY ("NUM" NOT NULL ENABLE);
